### ISSUE TITLE
TODO: Improve branch xb-dev

### ISSUE THREAD

**Issue by a-wing** [sb-im/sdwc#2]
branch: xb-dev

- [ ] Svg extraction and packaging
- [ ] flash rtmp lib
- [x] Merge plans.new && plans.edit 
- [ ] Change new plan button position
- [ ] submitPlan: https://github.com/SB-IM/SDWC/blob/xb-dev/src/pages/contents/plans/edit.vue#L122
- [ ] i18n Chinese && English

**Comment by a-wing** [comment]
- [ ] Responsive layout support (1920px, 1200px, 992px, 768px)
Tab span: 24

- depot && air
  - line 1 
    - 1920px { video: 8, weather: 16 }
    - 1200px { video: 16, weather: 8 }
    - 992px { video: 24, weather: 24 }
    - 768px { video: 24, weather: 24 }

**Comment by a-wing** [comment]
![image](https://user-images.githubusercontent.com/18189138/53491658-e40ace00-3ad1-11e9-84d3-3e5c5a2e7d9a.png)

- [ ] Dialog Confirm http://element-cn.eleme.io/#/en-US/component/dialog

> Click Dialog Confirm

**Comment by a-wing** [comment]
- [ ] Page Login  need status `Logging` Or `Login error`
- [ ] Global mqtt protocol support && Advanced control `json-rpc` https://github.com/SB-IM/SDWC/issues/4
- [ ] RSTP && websocket Video streaming support https://github.com/Streamedian/html5_rtsp_player
- [ ] Support for all request  authentication for oauth

**Comment by a-wing** [comment]
- [ ] Refactor config API.js

All API move to https://github.com/SB-IM/SDWC/blob/master/src/config/API.js


About  `/api/v1/plans/1/plan_logs`
https://github.com/SB-IM/SDWC/blob/master/src/pages/contents/plans/view.vue#L181
```javascript
let API = {
  'plans': '/api/v1/plans/:id',
  'missions': '/api/v1/plans/:plan_id/mission_logs/:id'

}

function gen(str, arr) {
  if (str.indexOf(":") !== -1 && arr.length != 0) {
    //console.log(str)
    let tmp = str.split('/')
    tmp[tmp.findIndex((ss) => {
      return ss.indexOf(":") !== -1
    })] = arr[0]

    //console.log(tmp.join('/'))

    return gen(tmp.join('/'), arr.slice(1))
  } else {
    return str
  }
}

function route(func, ...args) {
  return gen(API[func], args)
}

//route('plans', '1')

console.log(route('plans'))
// => /api/v1/plans/:id

console.log(route('plans', '2'))
// => /api/v1/plans/2

console.log(route('plans', '2', '3'))
// => /api/v1/plans/2

console.log(route('missions', '1', '2'))
// => /api/v1/plans/1/mission_logs/2
```

**Comment by a-wing** [comment]
All Done
